In [32]:
import numpy as np
import pandas as pd
import re

In [33]:
df=pd.read_csv('laptop_details.csv')

In [34]:
df.head()

,Product,Rating,MRP,Feature
0,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...,4.2,"₹36,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...
1,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...,4.2,"₹39,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...
2,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...,4.3,"₹32,990",Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...
3,HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...,4.4,"₹49,990",AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...
4,ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...,4.4,"₹49,990",Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...

In [35]:
df.shape

(720, 4)

In [36]:
df.describe()

           Rating
count  581.000000
mean     4.321170
std      0.282872
min      3.000000
25%      4.200000
50%      4.300000
75%      4.500000
max      5.000000

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  720 non-null    object
 1   Rating   581 non-null    float64
 2   MRP      720 non-null    object
 3   Feature  720 non-null    object
dtypes: float64(1), object(3)
memory usage: 22.6+ KB

In [38]:
df

,Product,Rating,MRP,Feature
0,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...,4.2,"₹36,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...
1,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...,4.2,"₹39,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...
2,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...,4.3,"₹32,990",Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...
3,HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...,4.4,"₹49,990",AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...
4,ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...,4.4,"₹49,990",Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...
...,...,...,...,...
715,ASUS Chromebook Flip Touch Celeron Dual Core -...,4.0,"₹23,490",Intel Celeron Dual Core Processor4 GB LPDDR4 R...
716,Lenovo IdeaPad Gaming 3 Ryzen 7 Octa Core AMD ...,4.5,"₹73,490",AMD Ryzen 7 Octa Core Processor8 GB DDR4 RAM64...
717,ASUS ROG Zephyrus G15 Ryzen 9 Octa Core 6900HS...,NaN,"₹1,94,990",AMD Ryzen 9 Octa Core Processor16 GB DDR5 RAM6...
718,ASUS Zenbook Flip 14 OLED (2022) Touch Panel C...,3.0,"₹1,25,990",Intel Core i7 Processor (12th Gen)16 GB LPDDR5...
719,Lenovo Ideapad Slim 3i Core i5 10th Gen - (8 G...,4.2,"₹50,990",Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...

In [80]:
# Extract features using refined regular expressions
# Extract entire processor names
# Extract entire processor names including values in and before the bracket
df['Processor'] = df['Feature'].str.extract(r'((Intel|AMD)[^\d]+ Core [^\d]+ Processor [^\d]+\([^)]+\))')
df['Processor'] = df['Processor'].str.strip()  # Remove leading/trailing spaces
df['RAM'] = df['Feature'].str.extract(r'(\d+ GB DDR4 RAM)')
df['Storage'] = df['Feature'].str.extract(r'(\d+ [^\d]+ SSD|\d+ [^\d]+ HDD)')
df['Operating_System'] = df['Feature'].str.extract(r'([^\d]+ Windows \d+ [^\d]+ Operating System)')
df['Display_Size'] = df['Feature'].str.extract(r'([\d.]+ [^\d]+ Display)')
df['Warranty'] = df['Feature'].str.extract(r'(\d+ Year [^\d]+Warranty)')

ValueError: Columns must be same length as key

In [79]:
# Display the first 5 rows of the resulting DataFrame
print(df[['Product', 'Processor', 'RAM', 'Storage', 'Operating_System', 'Display_Size', 'Warranty']].head())

                                             Product Processor            RAM  \
0  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...       NaN  8 GB DDR4 RAM
1  Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...       NaN  8 GB DDR4 RAM
2  ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...       NaN  8 GB DDR4 RAM
3  HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...       NaN  8 GB DDR4 RAM
4  ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...       NaN  8 GB DDR4 RAM

      Storage Operating_System        Display_Size                    Warranty
0  256 GB SSD              NaN    14 inch) Display  20212 Year Onsite�Warranty
1  512 GB SSD              NaN  15.6 inch) Display  20212 Year Onsite�Warranty
2  512 GB SSD              NaN  15.6 inch) Display  20211 Year Onsite Warranty
3  512 GB SSD              NaN  15.6 inch) Display      1 Year Onsite Warranty
4  512 GB SSD              NaN  15.6 inch) Display      1 Year Onsite Warranty

In [68]:
df.head()

,Product,Rating,MRP,Feature,RAM,Storage,Operating_System,Display_Size,Warranty,Processor
0,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 ...,4.2,"₹36,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,8 GB DDR4 RAM,256 GB SSD,NaN,14 inch) Display,20212 Year Onsite�Warranty,Intel Core i3 Processor (
1,Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 ...,4.2,"₹39,990",Intel Core i3 Processor (11th Gen)8 GB DDR4 RA...,8 GB DDR4 RAM,512 GB SSD,NaN,15.6 inch) Display,20212 Year Onsite�Warranty,Intel Core i3 Processor (
2,ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 ...,4.3,"₹32,990",Intel Core i3 Processor (10th Gen)8 GB DDR4 RA...,8 GB DDR4 RAM,512 GB SSD,NaN,15.6 inch) Display,20211 Year Onsite Warranty,Intel Core i3 Processor (
3,HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (...,4.4,"₹49,990",AMD Ryzen 5 Hexa Core Processor8 GB DDR4 RAM64...,8 GB DDR4 RAM,512 GB SSD,NaN,15.6 inch) Display,1 Year Onsite Warranty,AMD Ryzen 5 Hexa
4,ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/5...,4.4,"₹49,990",Intel Core i5 Processor (10th Gen)8 GB DDR4 RA...,8 GB DDR4 RAM,512 GB SSD,NaN,15.6 inch) Display,1 Year Onsite Warranty,Intel Core i5 Processor (

In [69]:
print(df['Processor'])

0      Intel Core i3 Processor (
1      Intel Core i3 Processor (
2      Intel Core i3 Processor (
3               AMD Ryzen 5 Hexa
4      Intel Core i5 Processor (
                 ...
715                          NaN
716                          NaN
717                          NaN
718    Intel Core i7 Processor (
719    Intel Core i5 Processor (
Name: Processor, Length: 720, dtype: object

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product           720 non-null    object
 1   Rating            581 non-null    float64
 2   MRP               720 non-null    object
 3   Feature           720 non-null    object
 4   RAM               561 non-null    object
 5   Storage           710 non-null    object
 6   Operating_System  0 non-null      object
 7   Display_Size      720 non-null    object
 8   Warranty          550 non-null    object
 9   Processor         418 non-null    object
dtypes: float64(1), object(9)
memory usage: 56.4+ KB